Random Forest Classification

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
ls

El volumen de la unidad D no tiene etiqueta.
 El n�mero de serie del volumen es: 4044-70FB

 Directorio de d:\Universidad\Cursos\Machine Learning. Curso Basico Machine Learning\Modelos\Random Forest

10/09/2020  04:47 p.�m.    <DIR>          .
10/09/2020  04:47 p.�m.    <DIR>          ..
10/09/2020  04:47 p.�m.               470 Ejercicio de Random Forest.ipynb
09/09/2020  05:21 p.�m.            12.895 vino.csv
               2 archivos         13.365 bytes
               2 dirs  722.070.958.080 bytes libres


In [5]:
vinos = pd.read_csv('vino.csv')

In [7]:
vinos.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

DIVISION DE LOS DATOS

In [9]:
X = vinos.drop('Wine Type', axis=1)
y = vinos['Wine Type']

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3)

ENTRENAMIENTO DEL MODELO

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
randomforest = RandomForestClassifier(n_estimators=80)

In [15]:
randomforest.fit(X_train, y_train)

RandomForestClassifier()

In [16]:
predicciones = randomforest.predict(X_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix

In [18]:
print(classification_report(y_test,predicciones))

precision    recall  f1-score   support

         One       1.00      1.00      1.00        17
       Three       0.88      1.00      0.94        15
         Two       1.00      0.91      0.95        22

    accuracy                           0.96        54
   macro avg       0.96      0.97      0.96        54
weighted avg       0.97      0.96      0.96        54



In [19]:
print(confusion_matrix(y_test, predicciones))

[[17  0  0]
 [ 0 15  0]
 [ 0  2 20]]


In [21]:
print('Training score {:.2f}'.format(randomforest.score(X_train, y_train)))
print('Test score {:.2f}'.format(randomforest.score(X_test, y_test)))

Training score 1.00
Test score 0.96
