INTRODUCCION NUMPY

In [2]:
import numpy as np

In [3]:
lista=[1,2,3,4]

In [4]:
array = np.array(lista)

In [5]:
array

array([1, 2, 3, 4])

In [6]:
lista2 = [[1,2,3,], [4,5,6],[7,8,9]]

In [7]:
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
array2 =np.array(lista2)

In [9]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#NUMPY METODOS
#Numpy Arrays

In [11]:
#Metodo arange
array = np.arange(5) #Genera Vector de 0 a 4

In [12]:
array

array([0, 1, 2, 3, 4])

In [13]:
np.arange(2,10) #Genera un vector de 2 a 9

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2,21,2) #Genera un vector de 2 a 9 de 2 en 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Metodo Zeros

In [15]:
np.zeros(3) #Genera un vector de ceros con tres elementos

array([0., 0., 0.])

In [16]:
np.zeros((3,4)) #Genera una matriz de ceros de 3x4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Metodo Ones

In [17]:
np.ones(3) #Genera un vector de unos con tres elementos

array([1., 1., 1.])

In [18]:
np.ones((3,4)) #Genera una matriz de unos de 3x4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Metodo Linspace

In [19]:
np.linspace(5,8,50) #Genera un vector de (inicio, fin, numero de elementos)

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

Metodo Eye

In [20]:
np.eye(5) #Genera una matriz identidad cuadrada

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Numeros Aleatorios

In [21]:

np.random.rand(5) #Genera vector de 5 elementos de numeros aleatorios

array([0.54735242, 0.327097  , 0.38398739, 0.40724306, 0.58908219])

In [22]:
np.random.rand(2,3) #Genera una matriz 2x3 de numeros aleatorios

array([[0.60136455, 0.17778741, 0.71578076],
       [0.21136655, 0.51942339, 0.86056345]])

In [23]:
np.random.randn(4) #Genera un vector random de 4 elemento con una distribucion normal

array([ 0.86812548,  1.42157008, -0.74692484, -0.23273278])

In [24]:
np.random.randn(4,5) #Genera matriz random de 4x5 elementos con una distribucion normal

array([[ 0.62376669,  0.1804871 , -0.17769084,  0.30711247,  1.44231236],
       [ 1.65024768, -0.53428224, -1.74060449,  1.09843211, -1.22934141],
       [ 2.03964837,  0.25228126,  1.94708627,  1.5906184 , -1.32477523],
       [ 0.48805926, -0.96558927,  0.99547844,  0.00952437, -0.66037326]])

Numpy Arrays - Numeros aleatorios enteros
Metodo randint

In [25]:
np.random.randint(1,20,10) #Genera numeros aleatorios enteros entre(inicio,fin, numero de elementos)

array([16, 16, 16, 14,  8, 18,  9,  3,  4,  9])

Numpy arrays - reshape
Metodo reshape

In [26]:

array = np.random.randint(1,100,25)
array

array([37, 39, 61, 48, 75, 88, 95, 68, 42, 92, 38, 30, 95,  7,  8,  2, 79,
       24, 94, 97,  2, 68, 45, 68, 36])

In [27]:
array.reshape(5,5) #Cambia la forma de un array (5x5)

array([[37, 39, 61, 48, 75],
       [88, 95, 68, 42, 92],
       [38, 30, 95,  7,  8],
       [ 2, 79, 24, 94, 97],
       [ 2, 68, 45, 68, 36]])

Numpy arrasy - max y min

In [30]:
array = np.random.randint(1,100,50)

In [31]:
array

array([91, 47, 61, 74, 67, 66, 50, 35, 82,  2, 82,  7, 99, 99, 32, 69, 95,
       43, 18, 80, 25, 33, 79, 29, 23, 66,  8,  7, 36, 23, 66, 67, 39, 88,
       74, 67, 50, 47, 81, 31, 44, 16, 17, 43, 61, 13, 12, 97, 91, 52])

In [32]:
valor_maximo = array.max()

In [33]:
valor_maximo

99

In [34]:
posicion_valor_maximo = array.argmax()

In [35]:
posicion_valor_maximo

12

In [36]:
valor_min = array.min()

In [37]:
valor_min

2

In [38]:
posicion_valor_minimo = array.argmin()

In [39]:
posicion_valor_minimo

9

Indexacion en arrays

In [42]:

array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
array[0]

0

In [44]:
array[1]

1

In [45]:
array[-1]

9

In [46]:
array[2:4]

array([2, 3])

In [47]:
array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
array[5:]

array([5, 6, 7, 8, 9])

In [50]:
array[:4]

array([0, 1, 2, 3])

In [55]:
array2 = array.copy()

In [56]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Indexacion de arrays de 2 o mas dimensiones

In [57]:

array = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [58]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
array[0]

array([1, 2, 3])

In [61]:
array[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
array[0,1]

2

In [63]:
array[0,0:2]

array([1, 2])

In [70]:
array[:2,:2]

array([[1, 2],
       [4, 5]])

Seleccionar elementos de un array según una condicion

In [77]:

array = np.arange(0,10)

In [78]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
condicion = array > 5

In [80]:
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [81]:
array[condicion]

array([6, 7, 8, 9])

In [82]:
array6 = array[condicion]

In [84]:
array6

array([6, 7, 8, 9])

In [86]:
array[array % 2 == 0]

array([0, 2, 4, 6, 8])

#Operaciones con arrays

In [88]:

array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
array + array #Suma

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [91]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [92]:
array * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [93]:
 array - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [94]:
array2 = np.arange(5,15)

In [95]:
array * array2

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [96]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])