EJERCICIO ARBOLES DE DECISION - CLASIFICACION

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pwd

'd:\\Universidad\\Cursos\\Machine Learning. Curso Basico Machine Learning\\Modelos\\JCHK'

In [4]:
vinos = pd.read_csv('vino.csv')
vinos.head(10)

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   
5    14.20        1.76  2.45               15.2      112.0           3.27   
6    14.39        1.87  2.45               14.6       96.0           2.50   
7    14.06        2.15  2.61               17.6      121.0           2.60   
8    14.83        1.64  2.17               14.0       97.0           2.80   
9    13.86        1.35  2.27               16.0       98.0           2.98   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   
5        3.39                  0.34             1.97             6.75  1.05   
6        2.52                  0.30             1.98             5.25  1.02   
7        2.51                  0.31             1.25             5.05  1.06   
8        2.98                  0.29             1.98             5.20  1.08   
9        3.15                  0.22             1.85             7.22  1.01   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One  
5                          2.85   1450.0       One  
6                          3.58   1290.0       One  
7                          3.58   1295.0       One  
8                          2.85   1045.0       One  
9                          3.55   1045.0       One

In [5]:
vinos['Wine Type'].unique()

array(['One', 'Two', 'Three'], dtype=object)

In [6]:
vinos['Wine Type'].value_counts()

Two      71
One      59
Three    48
Name: Wine Type, dtype: int64

DIVISION EN DATOS DE ENTRENAMIENTO Y DATOS DE PRUEBAS 

In [7]:
X= vinos.drop('Wine Type', axis=1)
y= vinos['Wine Type']

0        One
1        One
2        One
3        One
4        One
       ...  
173    Three
174    Three
175    Three
176    Three
177    Three
Name: Wine Type, Length: 178, dtype: object

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3)

ENTRENAMIENTO DEL MODELO

In [13]:
from sklearn.tree import DecisionTreeClassifier

In [14]:
arbol = DecisionTreeClassifier()
arbol.fit(X_train, y_train)

DecisionTreeClassifier()

In [15]:
predicciones = arbol.predict(X_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix

In [18]:
print(classification_report(y_test,predicciones))

precision    recall  f1-score   support

         One       1.00      0.88      0.94        17
       Three       0.88      0.93      0.90        15
         Two       0.91      0.95      0.93        22

    accuracy                           0.93        54
   macro avg       0.93      0.92      0.92        54
weighted avg       0.93      0.93      0.93        54



In [20]:
print(confusion_matrix(y_test, predicciones))

[[15  1  1]
 [ 0 14  1]
 [ 0  1 21]]


In [22]:
print('Training score {:.2f}'.format(arbol.score(X_train, y_train)))
print('Test score {:.2f}'.format(arbol.score(X_test, y_test)))

Training score 1.00
Test score 0.93
